In [ ]:
import numpy as np

print("Versão do Nunpy" , np.version.version)

# Manipulação em linhas e colunas:

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7] , [8, 9 , 1 , 2, 3, 4, 5]])

print(a)
print("Shape do meu array 2d" , a.shape)
a[0 , 3] 
# Para pegar um item específico, utilizamos a notação [Linha , Coluna]
#Lembrando que na programação, temos que começar contando do ZERO, então no exeplo temos:
#Linha 0 e 1
#Coluna de 0 a 6

In [ ]:
#para pegar a segunda linha, por exemplo:
a[1]

In [ ]:
#notação negatica
a[1 , -1]

In [ ]:
print(a)
# Pegar coluna específica
a[2 , :]

In [ ]:
# Metodo de slicing, de listas, tambem funciona no array

#[Start_index:end_index] -> step não é obrigatório
# // caso não queiramos adicionar o end index, é só colocar :

print(a)

a[0 , 5:]

In [ ]:
a [0, 1::2] #Pula de 2 em 2

# Desafios

Atividades: array, nupy 1d, 2d, shape e fatiamento

# 1. Array  1D <br>

a) crie um array numpy chamado 'Vetor' com os números de 10 a 50 de 10 em 10


b) imprimr o array


c) imprima o tamanho (Shape) desse array


d) imprima apenas os 3 primeiros elementos usando slicing


e) imprima os 2 ultimos elementos usando slicing

In [42]:
import numpy as np

Vetor = np.array([10 , 20 , 30 , 40 , 50])

print(Vetor)
print('O shape do array é:', Vetor.shape)

print("Os tres primeiros elementos é", Vetor[:3])

print('Os dois ultimos elementos são:', Vetor[3:])

[10 20 30 40 50]
O shape do array é: (5,)
Os tres primeiros elementos é [10 20 30]
Os dois ultimos elementos são: [40 50]


# 2. Array 2D

A) Crie um array chamado "Matriz" com duas linhas : a primeira [1, 2, 3] e a segunda [4, 5, 6]


B) Imprima o array


C) Imprima o shape da matriz


D) imprima apenas a segunda linha da matriz


E) Imprima apenas o elemento da primeira linha e a terceira coluna

In [51]:
import numpy as np

Matriz = np.array([[1, 2, 3] , [4, 5, 6]])

print(Matriz)
print()

print("O shape da matriz é:", Matriz.shape)
print()

print(Matriz[1, :])
print()

print(Matriz[0, 2])



[[1 2 3]
 [4 5 6]]

O shape da matriz é: (2, 3)

[4 5 6]

3
